<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllCache()
    {
        $qb = $this->createQueryBuilder('t');
        return $qb
            ->orderBy('t.readDate', 'DESC')
            ->getQuery()
            ->useResultCache(true, 24*60*60, 'all_books')
            ->getResult();
    }
}
